# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FiPay-eWallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FiPay-eWallet
  
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  
  pod 'Alamofire'
  
  target 'FiPay-eWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FiPay-eWalletUITests' do
    # Pods for testing
  end

end
